# Generated by Django 4.1.1 on 2022-09-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(default="False", max_length=255)),
                ("lastname", models.CharField(default="False", max_length=255)),
                ("email", models.EmailField(default="False", max_length=255)),
                ("password", models.CharField(default="False", max_length=255)),
                ("ContactNo", models.CharField(default="False", max_length=255)),
                ("oTP", models.IntegerField(default="", max_length=255)),
                ("oTPStatus", models.CharField(default="False", max_length=255)),
            ],
        ),
    ]
