# Generated by Django 4.1.1 on 2022-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendemail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="ContactNo",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="firstname",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="lastname",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
