# Generated by Django 4.1.1 on 2022-10-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendemail", "0002_alter_account_contactno_alter_account_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="image",
            field=models.ImageField(
                default="SuperAdmin/dummy.jpg", upload_to="SuperAdmin/"
            ),
        ),
        migrations.AlterField(
            model_name="account", name="oTP", field=models.IntegerField(default="0"),
        ),
    ]
